#!/usr/bin/env python

from blaz import Blaz
from sys import argv
from os import environ


def task(blaz):
    blaz.log()
    blaz.log('Inside ./run, argv is:')
    blaz.log(' '.join(argv))
    blaz.log()
    blaz.log('The current directory is:')
    blaz.run('pwd')
    blaz.log()
    blaz.log('The environment variables are:')
    blaz.run('env')
    blaz.log()
    blaz.log('Invoking task/start')
    environ['_BLAZ_SECRET2'] = 'secret_password_not_echoed_but_fowarded'
    blaz.cd('blaz/task')
    blaz.run('./start foo bar baz')

if __name__ == "__main__":
    environ['BLAZ_IMAGE'] = 'amiorin/alpine-blaz:latest'
    environ['BLAZ_CHDIR_REL'] = '..'
    environ['BLAZ_DONT_PULL'] = ''
    environ['BLAZ_VARS'] = 'JENKINS_BUILD GIT_COMMIT'
    environ['JENKINS_BUILD'] = '1'
    environ['GIT_COMMIT'] = '2'
    b = Blaz()
    if b.before():
        b.log("before")
    if b.after():
        b.log("after")
    b.invoke(task)
