#!/usr/bin/env python3

from blaz import Blaz
from sys import argv
from os import environ


def task(blaz):
    blaz.run('./run-with-error-nested')

if __name__ == "__main__":
    environ['BLAZ_DONT_PULL'] = ''
    b = Blaz()
    b.invoke(task)
